# Generated by Django 2.1.7 on 2019-03-26 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final', models.BooleanField(default=False, verbose_name='Choice Finalized')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('B', 'Byte'), ('b', 'Bite')], max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='choice',
            name='choosee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choosee', to='internal.Profile'),
        ),
        migrations.AddField(
            model_name='choice',
            name='chooser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chooser', to='internal.Profile'),
        ),
    ]
