# Generated by Django 2.1.7 on 2019-03-26 19:17

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0002_sitesettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name_plural': 'Site Settings'},
        ),
        migrations.AddField(
            model_name='profile',
            name='answers',
            field=django.contrib.postgres.fields.jsonb.JSONField(default='["answer1", "answer2"]'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='questions',
            field=django.contrib.postgres.fields.jsonb.JSONField(default='["question1", "question2"]'),
        ),
    ]
