# Generated by Django 2.1.7 on 2019-03-26 19:20

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import internal.models


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0003_auto_20190326_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='answers',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='questions',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=internal.models.questions),
        ),
    ]
