# Generated by Django 2.2 on 2019-04-01 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0005_auto_20190401_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='points',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
    ]
