# Generated by Django 2.1.7 on 2019-04-02 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0006_team_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='final',
        ),
        migrations.RemoveField(
            model_name='team',
            name='byte',
        ),
        migrations.AddField(
            model_name='profile',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='internal.Team'),
        ),
    ]
