# Generated by Django 2.1.7 on 2019-04-02 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0007_auto_20190402_2021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='points',
        ),
    ]
