# Generated by Django 2.1.7 on 2019-04-04 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0008_remove_team_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='questions',
        ),
    ]
