# Generated by Django 2.1.7 on 2019-04-11 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0012_auto_20190408_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='repeatable',
            field=models.BooleanField(default=False),
        ),
    ]
