# Generated by Django 2.1.7 on 2019-04-28 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0015_auto_20190422_0048'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCompletion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Completion', max_length=200)),
                ('repeatable', models.BooleanField(default=False)),
                ('points', models.IntegerField()),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='internal.Event')),
            ],
        ),
        migrations.AddField(
            model_name='eventcheckoff',
            name='event_completion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='internal.EventCompletion'),
        ),
    ]
